spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: notification-service
server:
  port: ${NOTIFICATION_SERVICE_PORT:8086}
management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    rw.rra.roomiq: INFO
