spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: analytics-service
server:
  port: ${ANALYTICS_SERVICE_PORT:8088}
management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    rw.rra.roomiq: INFO
